# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

class Attribute(object):
    NONE = 0
    PoolAttribute = 1
    ConvAttribute = 2
    TransposeConvAttribute = 3
    PadAttribute = 4
    AxisAttribute = 5
    ReshapeAttribute = 6
    SliceAttribute = 7
    TileAttribute = 8
    ResizeAttribute = 9
    ClampAttribute = 10
    RescaleAttribute = 11
    MulAttribute = 12
    ArithmeticRightShiftAttribute = 13
    CondIfAttribute = 14
    WhileLoopAttribute = 15
    TransposeAttribute = 16
    TableAttribute = 17
    MatMulAttribute = 18
    FullyConnectedAttribute = 19
    NegateAttribute = 20
    CustomAttribute = 21
    FFTAttribute = 22
