# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers

class CondIfAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCondIfAttribute(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CondIfAttribute()
        x.Init(buf, n + offset)
        return x

    # CondIfAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CondIfAttribute
    def ThenBranch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CondIfAttribute
    def ElseBranch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CondIfAttributeStart(builder): builder.StartObject(2)
def CondIfAttributeAddThenBranch(builder, thenBranch): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(thenBranch), 0)
def CondIfAttributeAddElseBranch(builder, elseBranch): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(elseBranch), 0)
def CondIfAttributeEnd(builder): return builder.EndObject()
