# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MatMulAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MatMulAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMatMulAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MatMulAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # MatMulAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MatMulAttribute
    def AZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MatMulAttribute
    def BZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MatMulAttributeStart(builder):
    builder.StartObject(2)

def Start(builder):
    MatMulAttributeStart(builder)

def MatMulAttributeAddAZp(builder, aZp):
    builder.PrependInt32Slot(0, aZp, 0)

def AddAZp(builder, aZp):
    MatMulAttributeAddAZp(builder, aZp)

def MatMulAttributeAddBZp(builder, bZp):
    builder.PrependInt32Slot(1, bZp, 0)

def AddBZp(builder, bZp):
    MatMulAttributeAddBZp(builder, bZp)

def MatMulAttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return MatMulAttributeEnd(builder)
