# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers

class MatMulQuantInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMatMulQuantInfo(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MatMulQuantInfo()
        x.Init(buf, n + offset)
        return x

    # MatMulQuantInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MatMulQuantInfo
    def AZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MatMulQuantInfo
    def BZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MatMulQuantInfoStart(builder): builder.StartObject(2)
def MatMulQuantInfoAddAZp(builder, aZp): builder.PrependInt32Slot(0, aZp, 0)
def MatMulQuantInfoAddBZp(builder, bZp): builder.PrependInt32Slot(1, bZp, 0)
def MatMulQuantInfoEnd(builder): return builder.EndObject()
