# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tosa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NegateAttribute(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NegateAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNegateAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NegateAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x4F\x53\x41", size_prefixed=size_prefixed)

    # NegateAttribute
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NegateAttribute
    def Input1Zp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # NegateAttribute
    def OutputZp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def NegateAttributeStart(builder):
    builder.StartObject(2)

def Start(builder):
    NegateAttributeStart(builder)

def NegateAttributeAddInput1Zp(builder, input1Zp):
    builder.PrependInt32Slot(0, input1Zp, 0)

def AddInput1Zp(builder, input1Zp):
    NegateAttributeAddInput1Zp(builder, input1Zp)

def NegateAttributeAddOutputZp(builder, outputZp):
    builder.PrependInt32Slot(1, outputZp, 0)

def AddOutputZp(builder, outputZp):
    NegateAttributeAddOutputZp(builder, outputZp)

def NegateAttributeEnd(builder):
    return builder.EndObject()

def End(builder):
    return NegateAttributeEnd(builder)
